version: '3'

services:
  db:
    image: postgres

  backend:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  migration:
    build: ./backend
    command: python manage.py migrate
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
